### ISSUE TITLE
Todoist Flatpak stopped working on latest release

### ISSUE THREAD

**Issue by cig0** [flathub/com.todoist.Todoist#29]
Hi,

Please find below crash information and environment execution specs:

Todoist Flatpak version: `1.0.9`
Branch: `stable`
Origin: `Flathub`
Installation: `user` 

```
~ % flatpak run --branch=stable --arch=x86_64 --command=todoist --file-forwarding com.todoist.Todoist @@u %U @@
[0509/082615.944560:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
/app/bin/todoist: line 10:     3 Trace/breakpoint trap   (core dumped) env TMPDIR="$XDG_RUNTIME_DIR/app/$FLATPAK_ID" zypak-wrapper /app/extra/todoist/todoist $FLAGS "$@"


After allowing using ptrace:

~ % flatpak run --branch=stable --arch=x86_64 --command=todoist --file-forwarding com.todoist.Todoist @@u %U @@
[0509/082856.943102:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0509/082856.943157:ERROR:elf_dynamic_array_reader.h(64)] tag not found
/app/bin/todoist: line 10:     3 Trace/breakpoint trap   (core dumped) env TMPDIR="$XDG_RUNTIME_DIR/app/$FLATPAK_ID" zypak-wrapper /app/extra/todoist/todoist $FLAGS "$@"
```

I tried a `flatpak repair` followed by an uninstall -> install, to no avail.

Execution context specs:
Flatpak version: `1.15.4`
OS: `Fedora 38 Kinoite Universal Blue` (a flavor of Silverblue/Kinoite)
Display manager: `Wayland`
DE: `KDE Plasma 5.27.4`
GPU: `NVIDIA 530.41.03`

I'll be happy to help to get this Flatpak up and running again :)
Thanks!

**Comment by jurf** [comment]
Does this still happen? Cannot reproduce.

**Comment by cig0** [comment]
Hi, it is working as expected now @jurf. Thanks for the follow-up.
