### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by DarkArc** [flathub/com.todoist.Todoist#7]
The current auth flow seems to require going through the browser, however, on Fedora 33 KDE with both Firefox and Chromium I don't get redirected back to the app properly, so I can't login.

**Comment by dgmulf** [comment]
I get the same error on Manjaro GNOME 21.0.2.

**Comment by jurf** [comment]
Thanks for the report, I’ll try reproducing this later. I did not have any issue logging in with previous versions and the auth is retained through upgrades, so I missed it when testing.

**Comment by jurf** [comment]
Hey, I managed to reproduce and fix this, please reopen if it does not work for you.

**Comment by DarkArc** [comment]
I'm still having trouble with this, it might be because my desktop doesn't integrate with flatpak well though (it doesn't automatically pull in the desktop files, I've always had to create launchers for flatpak run).

**Comment by jurf** [comment]
You’re going to have to pull in the desktop files somehow, as Todoist has to register itself as the URL scheme handler.
